import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaderNavigation from "../../../components/admin/HeaderNavigation";
import SideNavigation from "../../../components/admin/SideNavigation";
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <div>
                  <div><HeaderNavigation /></div>
              </div>
               <div>
                    <div className="grid grid-cols-6">
                      <div className="col-span-1">

                        <SideNavigation />
                      </div>
                        <div className="px-2 @3xl:px-10 @3xl:col-span-5 col-span-5">
                            {children}
                        </div>
                    </div>
                  </div>
      </body>   
    </html>
  );
}
